name: Repository Policy Check

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  policy:
    name: Run repository policy checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run repository policy checks
        uses: qualcomm/repo-policy-action@d5daf4f9b44a503043e447c2e227b45fdeca2167
        with:
          fail-on-error: 'true'
          fail-on-warning: 'false'
