name: Repository Policy Check

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  policy:
    name: Run repository policy checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run repository policy checks
        uses: qualcomm/repo-policy-action@72c9c6dc64607153cda24e9f6d3f8e115c1a4a29
        with:
          fail-on-error: 'true'
          fail-on-warning: 'false'
